### ISSUE TITLE
Creating gff from genePred returns error

### ISSUE THREAD

**Issue by adomingues** [yarden/rnaseqlib#12]
I was trying to create custom miso annotation using [these instructions](https://rnaseqlib.readthedocs.org/en/clip/#creating-custom-gff-annotations-for-miso) but got the following error:

``` shell
python /local/data/home/adomingu/env/lib/python2.7/site-packages/rnaseqlib/gff/gff_make_annotation.py ./ ./gff --flanking-rule commonshortest --genome-label Zv9.junker
Making GFF alternative events annotation...
  - UCSC tables read from: /fsimb/groups/imb-kettinggr/genomes/Danio_rerio/Ensembl/Zv9/Annotation/Archives/archive-2014-05-23-16-02-26/Genes/miso
  - Output dir: /fsimb/groups/imb-kettinggr/genomes/Danio_rerio/Ensembl/Zv9/Annotation/Archives/archive-2014-05-23-16-02-26/Genes/miso/gff
Loaded 1 UCSC tables.
Loading tables...
Traceback (most recent call last):
  File "/local/data/home/adomingu/env/lib/python2.7/site-packages/rnaseqlib/gff/gff_make_annotation.py", line 65, in <module>
    main()
  File "/local/data/home/adomingu/env/lib/python2.7/site-packages/rnaseqlib/gff/gff_make_annotation.py", line 61, in main
    make_annotation(args)
  File "/local/data/home/adomingu/env/lib/python2.7/site-packages/rnaseqlib/gff/gff_make_annotation.py", line 35, in make_annotation
    sanitize=args.sanitize)
  File "/local/data/home/adomingu/env/local/lib/python2.7/site-packages/rnaseqlib/events/defineEvents.py", line 933, in defineAllSplicing
    sg = splicegraph.SpliceGraph(table_fnames)
  File "/local/data/home/adomingu/env/local/lib/python2.7/site-packages/rnaseqlib/events/SpliceGraph.py", line 446, in __init__
    self.load_tables()
  File "/local/data/home/adomingu/env/local/lib/python2.7/site-packages/rnaseqlib/events/SpliceGraph.py", line 496, in load_tables
    self.tables[table_label] = parseTables.readTable(table_fname)
  File "/local/data/home/adomingu/env/local/lib/python2.7/site-packages/rnaseqlib/events/parseTables.py", line 56, in readTable
    for col_num in range(len(header))])
IndexError: list index out of range
```

Since was converting  GTF to genePred using `gtfToGenePred -genePredExt  gtf genepred` and the output was not exactly the same as represented in rnaseqlib's intructions:

``` shell
gtfToGenePred -genePredExt Danio_rerio.Zv9.74.ImprovedUTRs.Junker_et_al_2014.noZv.so.gtf ensGene.txt
head ensGene.txt
ENSDART00000152494      chr1    -       2286    4806    4806    4806    2       2286,4578,      2340,4806,      0       ENSDARG00000096573      none     none    -1,-1,
ENSDART00000152276      chr1    +       3799    15148   15148   15148   8       3799,4645,5177,5532,6246,9049,9239,13072,       3930,4809,5202,5646,6393,9141,9360,15148,        0       ENSDARG00000076045      none    none    -1,-1,-1,-1,-1,-1,-1,-1,
ENSDART00000109479      chr1    +       3799    15138   15138   15138   9       3799,4645,5177,5532,6246,11049,11239,13072,14304,       3930,4809,5202,5646,6393,11141,11360,13958,15138,        0       ENSDARG00000076045      none    none    -1,-1,-1,-1,-1,-1,-1,-1,-1,
```

I tested it further using (i) the ensGene track from UCSC downloaded for both Zv9 and hg19; (ii) a file with the example genePred in the help page. All failed with the same message. 

I have no idea of what the problem is.

**Comment by adomingues** [comment]
Unrelated, I have installed rnaseqlib using `easy_install rnaseqlib`  inside a virtualenv, and even though I can import it in the python console none of the python scripts seem to be available in $PATH. This is silly, but how can I add rnaseqlib to path? (other than doing one by one for all relevant scripts)

**Comment by yarden** [comment]
Why use easy_install inside a virtualenv? Have you tried pip? I install it with pip/virtualenv and the scripts then get placed in executables that should be in your `PATH` (assuming you've loaded the virtualenv with `source`)

**Comment by adomingues** [comment]
I used easy_install because that was in the instructions :) Also the pip package does not seem to be available :

``` bash
source ~/env/bin/activate
pip install rnaseqlib
Collecting rnaseqlib
  Could not find a version that satisfies the requirement rnaseqlib (from versions: )
  No matching distribution found for rnaseqlib
```

Unless I should install it from source.

**Comment by adomingues** [comment]
For posterity, the issue relating to create a gff from the output of `gtfToGenePred -genePredExt gtf genepred` happens because the output file does not contain a "bin" field (the first one in the UCSC gp format). The solution I found was to add an extra mock column to the output of `gtfToGenePred` with `sed -i 's/^/\.\t/' ensGene.txt`.
