### ISSUE TITLE
ERROR: python setup.py install --prefix=/somewhere

### ISSUE THREAD

**Issue by ifantasy** [yarden/rnaseqlib#15]
When I typed the command ``python setup.py install --prefix=/somewhere/rnaseqlib-clip``, the first lines were presented as follows:
```
/somewhere/anaconda2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/somewhere/anaconda2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
```
Why it said that `'entry_points'` and ``install_requires`` were unknown?

Two directories ``bin`` and ``build`` were generated in ``/somewhere/rnaseqlib-clip``. In ``bin``, there were only two files, ``gtf2gff3.pl`` and ``ucsc_table2gff3.pl``. 

I typed ``/somewhere/rnaseqlib-clip/build/lib/rnaseqlib/gff/gff_make_annotation.py --help``, but error messages made me frustrated.
```
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import: unable to open X server `' @ error/import.c/ImportImageCommand/368.
/somewhere/rnaseqlib-clip/build/lib/rnaseqlib/gff/gff_make_annotation.py: line 15: syntax error near unexpected token `('
/somewhere/rnaseqlib-clip/build/lib/rnaseqlib/gff/gff_make_annotation.py: line 15: `def make_annotation(args):'
```

I knew I didn't install ``rnaseqlib`` successfully. How to solve this? 
P.S. All packages in ``install_requires`` had been already installed.

**Comment by ifantasy** [comment]
I also tried to modify the headline of setup.py (``distutils.core`` was replaced by ``setuptools``), but errors still existed as I typed ``bin/gff_make_annotation``, though the two ``UserWarning`` messages disappeared and ``gff_make_annotation`` as well as other execute files were generated in ``bin``.
```
Traceback (most recent call last):
  File "bin/gff_make_annotation", line 9, in <module>
    load_entry_point('rnaseqlib==0.1', 'console_scripts', 'gff_make_annotation')()
  File "/somewhere/anaconda2/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/somewhere/anaconda2/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/somewhere/anaconda2/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/somewhere/rnaseqlib-clip/lib/python2.7/site-packages/rnaseqlib-0.1-py2.7.egg/rnaseqlib/gff/gff_make_annotation.py", line 12, in <module>
    import rnaseqlib.events.defineEvents as def_events
  File "/somewhere/rnaseqlib-clip/lib/python2.7/site-packages/rnaseqlib-0.1-py2.7.egg/rnaseqlib/events/defineEvents.py", line 5, in <module>
    import parseTables
  File "/somewhere/rnaseqlib-clip/lib/python2.7/site-packages/rnaseqlib-0.1-py2.7.egg/rnaseqlib/events/parseTables.py", line 5, in <module>
    import rnaseqlib.tables as tables
  File "/somewhere/rnaseqlib-clip/lib/python2.7/site-packages/rnaseqlib-0.1-py2.7.egg/rnaseqlib/tables.py", line 24, in <module>
    import rnaseqlib.gff.gffutils_helpers as gffutils_helpers
  File "/somewhere/rnaseqlib-clip/lib/python2.7/site-packages/rnaseqlib-0.1-py2.7.egg/rnaseqlib/gff/gffutils_helpers.py", line 24, in <module>
    import pybedtools
  File "/somewhere/anaconda2/lib/python2.7/site-packages/pybedtools-0.7.9-py2.7-linux-x86_64.egg/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /somewhere/anaconda2/lib/python2.7/site-packages/pybedtools-0.7.9-py2.7-linux-x86_64.egg/pybedtools/cbedtools.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

**Comment by edkonyakhina** [comment]
@ifantasy 
Did you find a solution of this problem? I have the same.

**Comment by 1409605824** [comment]
I have the same problem,have you solved it ??

**Comment by 1409605824** [comment]
> @ifantasy
> Did you find a solution of this problem? I have the same.

have you solved the problem?
